service: bmt-media-shop-service-test-dir

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: serverless-profile


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
        - s3:DeleteObject
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "*"

  environment:
    BUCKET: ${self:service}-templates
    PDF_BUCKET: ${self:service}-pdf
    REVIEW_TABLE: ${self:service}-review
    PROMOCODE_TABLE: ${self:service}-promocode
    USER_TABLE: ${self:service}-user
    ORDER_TABLE: ${self:service}-order

package:
  include:
    - wkhtmltopdf

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true
  s3:
    port: 8800
    directory: /tmp
    cors: true
  remover:
     buckets:
       - ${self:provider.environment.BUCKET}
       - ${self:provider.environment.PDF_BUCKET}

custom:
#  webpackIncludeModules: true
  documentation:
    raml:
      title: BMT media-shop API
      version: v1.0
  dirconfig:
      quiet: false

plugins:
  - serverless-plugin-typescript
  - serverless-dir-config-plugin
  - serverless-dynamodb-local
  - serverless-s3-local
  - serverless-offline
  - serverless-s3-remover