service: bmt-media-shop-service-unit-tests

provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: serverless-profile


  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::*"
    - Effect: "Allow"
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:DeleteItem
        - dynamodb:UpdateItem
      Resource: "*"

  environment:
    BUCKET: ${self:service}-templates
    PDF_BUCKET: ${self:service}-pdf
    REVIEWS_TABLE: ${self:service}-table-reviews
    PROMOCODE_TABLE: ${self:service}-promocode
    USERS_TABLE: ${self:service}-users

package:
  include:
    - wkhtmltopdf

custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      migrate: true

functions:
  auth:
    handler: api/auth/handler.auth

  print:
    handler: api/print.receipt
    events:
      - http:
          path: receipt
          method: post
          integration: lambda
          cors: true

  createPromocode:
    handler: api/promocode/handler.create
    events:
      - http:
          path: promocode/create
          method: put
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  checkPromocode:
      handler: api/promocode/handler.check
      events:
        - http:
            path: promocode/check
            method: put
            integration: lambda
            cors: true
            authorizer:
              name: auth
              resultTtlInSeconds: 0

  getPromocode:
      handler: api/promocode/handler.get
      events:
        - http:
            path: promocode/get
            method: get
            integration: lambda
            cors: true
            authorizer:
              name: auth
              resultTtlInSeconds: 0

  removePromocode:
    handler: api/promocode/handler.remove
    events:
      - http:
          path: promocode/remove
          method: delete
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  getAllItems:
    handler: api/auth/handler.getAllProfiles
    events:
      - http:
          path: api/profile/getAll
          method: get
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  getProfile:
    handler: api/auth/handler.getProfile
    events:
      - http:
          path: api/profile/get
          method: get
          integration: lambda
          cors: true
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  updateProfile:
    handler: api/auth/handler.updateProfile
    events:
      - http:
          method: post
          path: api/profile/update
          cors: true
          integration: lambda
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  createProfile:
    handler: api/auth/handler.createProfile
    events:
      - http:
          method: post
          path: api/profile/create
          cors: true
          integration: lambda
          authorizer:
            name: auth
            resultTtlInSeconds: 0

  getSelling:
      handler: api/admin.getSelling

      events:
        - http:
            path: api/admin/getSelling
            method: get
            integration: lambda
            cors: true

  addReview:
    handler: api/reviews/handler.add
    events:
      - http:
          path: reviews/add
          method: post
          integration: lambda
          cors: true

  getReviews:
      handler: api/reviews/handler.getByProductID
      events:
        - http:
            path: reviews/{productID}
            method: get
            integration: lambda
            cors: true

resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PDF_BUCKET}
    TemplatesBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.BUCKET}
    PromocodeDynamoDb:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "social"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "social"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: ${self:provider.environment.PROMOCODE_TABLE}

    usersTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: ${self:provider.environment.USERS_TABLE}
        AttributeDefinitions:
          - AttributeName: "id"
            AttributeType: "S"
          - AttributeName: "social"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "id"
            KeyType: "HASH"
          - AttributeName: "social"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

    ReviewsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.REVIEWS_TABLE}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline

