service: bmt-media-shop-service-os
provider:
  name: aws
  runtime: nodejs6.10
  region: eu-central-1
  profile: serverless-profile
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
        - "s3:PutObject"
        - "s3:PutObjectAcl"
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:GetItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:ListStreams
        - dynamodb:DescribeStream
      Resource: "*"
  environment:
    BUCKET: ${self:service}-templates
    PDF_BUCKET: ${self:service}-pdf
    TABLE_REVIEWS: ${self:service}-table-reviews
package:
  include:
    - wkhtmltopdf
functions:
  print:
    handler: api/print.receipt
    events:
      - http:
          path: receipt
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
  notification:
    handler: api/notification.sendmail
    events:
      - http:
          path: notification
          method: get
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
  addReview:
    handler: api/reviews.add
    events:
      - http:
          path: reviews/add
          method: post
          integration: lambda
          cors: true
          response:
            headers:
              Access-Control-Allow-Origin: "'*'"
  getReviews:
      handler: api/reviews.getProductID
      events:
        - http:
            path: reviews/{productID}
            method: get
            integration: lambda
            cors: true
            response:
              headers:
                Access-Control-Allow-Origin: "'*'"
  reviewsTrigger:
      handler: api/reviews.reviewsTrigger
      events:
        - stream:
            type: dynamodb
            arn:
              Fn::GetAtt: [ "ReviewsDynamoDBTable", "StreamArn" ]
resources:
  Resources:
    NewResource:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:provider.environment.PDF_BUCKET}
    ReviewsDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:provider.environment.TABLE_REVIEWS}
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES
plugins:
  - serverless-plugin-typescript